### ISSUE TITLE
[BUG]　“Despite setting the MRTK3 profile, I’m getting an error saying ‘MRTK Profile could not be retrieved’

### ISSUE THREAD

**Issue by HoloMoto** [MixedRealityToolkit/MixedRealityToolkit-Unity#577]
## Describe the bug

 In my Unity project using MRTK3, when I place the MRTK XR Rig and MRTK Input Simulator objects and run the scene, it goes into a pause state. Despite setting the MRTK profile, I’m getting the following error indicating that it’s not being retrieved correctly.

```
MRTK Profile could not be retrieved.
UnityEngine.Debug:LogError (object)
MixedReality.Toolkit.XRSubsystemHelpers:GetConfiguration<MixedReality.Toolkit.Input.SyntheticHandsConfig, MixedReality.Toolkit.Input.SyntheticHandsSubsystem> () (at ./Library/PackageCache/org.mixedrealitytoolkit.core@c00d0949582c/Utilities/XRSubsystemHelpers.cs:282)
MixedReality.Toolkit.Input.SyntheticHandsSubsystem:Register () (at ./Library/PackageCache/org.mixedrealitytoolkit.input@719fc273754c/Subsystems/SyntheticHands/SyntheticHandsSubsystem.cs:50)
```

```
No profile is available. Please ensure a profile is assigned in the MRTK settings or file a bug if one is and this error is still occurring.
UnityEngine.Debug:LogError (object)
MixedReality.Toolkit.Subsystems.MRTKLifecycleManager:Awake () (at ./Library/PackageCache/org.mixedrealitytoolkit.core@c00d0949582c/Subsystems/MRTKLifecycleManager.cs:49)
```

<img width="1432" alt="Screenshot 2023-12-02 212901" src="https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/36409613/b67c2a89-37e4-4b8d-9be3-fd0d634aee57">

Strangely enough, this error is resolved as soon as I open the MRTK3 item in ProjectSettings, even if I don’t change any scene settings.

However, when I restart Unity, the error occurs until I open ProjectSettings.

It’s just a guess, but I get the impression that I can’t access the MRTK profile due to some influence.

## To reproduce

1. Run MRTK3 Scene in UnityEditor
2. The scene is paused and the aforementioned error occurs.
3. Open Project Settings and display the MRTK3 menu
4.  from step 3, the error is resolved until Unity is restarted again.

## Your setup (please complete the following information)

- Unity Version 2022.3.5f1 (URP)
- MRTK Version 
<img width="416" alt="Screenshot 2023-12-02 213200" src="https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/36409613/ab9fa296-72ec-4857-9b6c-6bb0cecfa55d">

- Windows11PC

## Target platform (please complete the following information)

- UnityEditor

**Comment by ms-RistoRK** [comment]
Hello @HoloMoto, thank you for reaching out.  Could you please confirm if you have your MRTK profile set in both Universal Windows Platform and Windows settings? for example:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/fd3730ce-2619-4c8a-a8fd-7daf16d514bf)

and also 

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/7920f5eb-eada-47a8-a59b-8105e8db8201)

**Comment by HoloMoto** [comment]
@ms-RistoRK 
Hello! Yes I’ve checked and it’s definitely set for both UWP and standalone. I’ve restarted my PC and such, but it keeps happening.

<img width="1514" alt="image" src="https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/36409613/fac5e6b1-58ca-4200-bcf5-0809452c7579">

**Comment by ms-RistoRK** [comment]
> @ms-RistoRK Hello! Yes I’ve checked and it’s definitely set for both UWP and standalone. I’ve restarted my PC and such, but it keeps happening.
> 
> <img alt="image" width="1514" src="https://private-user-images.githubusercontent.com/36409613/288587406-fac5e6b1-58ca-4200-bcf5-0809452c7579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDMxNTMsIm5iZiI6MTcwMjAwMjg1MywicGF0aCI6Ii8zNjQwOTYxMy8yODg1ODc0MDYtZmFjNWU2YjEtNThjYS00MjAwLWJjZjUtMDgwOTQ1MmM3NTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMzQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNDFjNWQwYTI3ZTBmNTVkYWFjMzVkMjkzYjZkYzQyMjM5YzY2MjRjMTEyMGM1NzlmNmI2MzkyMmE5NTY1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3KhI4ppAneEHRTaGyH5pDj5NaOq8v6pP0jv-x8rxT7U">

Thank you for the clarification @HoloMoto .  Is there a project + scene you could share with the issue? I want to try and reproduce it on my side.

**Comment by HoloMoto** [comment]
@ms-RistoRK   I will share my project occued this error.
https://github.com/HoloMoto/HoloLens_To_iOS_ConnectTest

It occurs reproducibly in my local environment.　If I can't reproduce it, I will provide any information you might be able to identify about the bug, such as my PC settings.

**Comment by ms-RistoRK** [comment]
Hello @HoloMoto thank you for providing the link to the repository.  I cloned the repo and attempted to reproduce the issue, but I was unable to reproduce the issue.  I opened "SampleScene" from Assets/Scenes and when running from Unity Editor no error about MRTK profile appeared in the Editor's Console.  May I suggest that you run a 'git status' on your repository root folder? For example:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/84108471/42f0161d-a9ed-4a33-936e-d04da836b283)
This would help us see what other files have changed.

**Comment by AMollis** [comment]
Also @HoloMoto , can you confirm that all of your platforms have a MRTK profile set (iOS, Android, UWP, Standalone)

**Comment by enesbunyamincelik** [comment]
I have been facing the same issue as I have added the MRTK profile to all platforms. The problem was fixed. @HoloMoto

**Comment by anonymous2585** [comment]
On my side, I added a log in the `MRTKSettings.OnEnable()` function.
When I have the error `MRTK Profile could not be retrieved.` on enter playmode, my log doesn't appear in the console.
When it works (most of the time), the log is the first logged in the console.

For some reason, sometimes Unity doesn't call the `MRTKSettings.OnEnable()` function when entering playmode (or maybe it's called to early, before domain reload reset the static field). When I select the asset in the project window, the `OnEnable()` function is called and I don't have the error on the next playmode start.

(I have all profiles set for all my platforms.)

**Comment by Daniel4144** [comment]
I am getting the same error sometimes in playmode (with and without Holographic Remoting). The MRTK profile is assigned to all installed platforms (Windows, UWP). Selecting the MRTK profile asset fixes the error for some time. Restarting the editor has no effect.
(Unity 2022.3.12f1)

**Comment by ms-RistoRK** [comment]
Attempted another reproduction with Unity 2022.3.7f1, commit https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/commit/f279218d1e1f0856ebb32c6122b0b22a273a15d6 on a fresh install and a fresh repo clone.
Still unable to reproduce.  Closing this issue, please file a new issue if this happens again.

**Comment by GGsparta** [comment]
For anyone still having the issue, here's the thing I went through :
If you need to use another profile than the default one, you can create one. Everything will seem fine in the inspector but via the `Project Settings > MRTK3` panel, click on the subsystems and you will see you have to assign a profile for them. You can only assign them through this panel. Create each sub-profile in the project by `Right Click > Create > MRTK > Subsystems`.
Hope this will be helpful.

**Comment by ms-RistoRK** [comment]
[like]  Risto Rangel reacted to your message:
________________________________
